version: "2"
name: to delete rp
canonical: to_delete_rp
author: robert_parkin
status: private
description: test stack rp
image: ""
keywords:
- test
- provider:aws
technologies: []
dependencies: []
config:
  default:
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      to_delete_rp:
        destination: ($ project $)/terraform/($ environment $)/to_delete_rp.tf
        path: terraform/default/to_delete_rp.tf.sample
