version: 2
use_cases:
- name: default
  sections:
  - name: Resource
    groups:
    - name: application
      technologies: [terraform]
      vars:
      - name: "Virtual network"
        description: "Select multiple AWS VPC in which to deploy this environment sub network."
        key: resource_widget_example
        widget: cy_inventory_resource
        type: string
