version: "2"
use_cases:
- name: default
  sections:
  - name: terraform
    groups:
    - name: application
      technologies: [terraform]
      vars:
      - name: "Azure Subscription ID"
        description: "The azure subscription id used to deploy the infrastructure. Make sure to select the correct key."
        key: azure_subscription_id
        widget: cy_cred
        widget_config:
          cred_types:
            - azure
        type: string
        required: true
      - name: "Azure Tenant ID"
        description: "The azure tenant id used to deploy the infrastructure. Make sure to select the correct key."
        key: azure_tenant_id
        widget: cy_cred
        widget_config:
          cred_types:
            - azure
        type: string
        required: true
      - name: "Azure Client ID"
        description: "The azure client id used to deploy the infrastructure. Make sure to select the correct key."
        key: azure_client_id
        widget: cy_cred
        widget_config:
          cred_types:
            - azure
        type: string
        required: true
      - name: "Azure Client Secret"
        description: "The azure client secret used to deploy the infrastructure. Make sure to select the correct key."
        key: azure_client_secret
        widget: cy_cred
        widget_config:
          cred_types:
            - azure
        type: string
        required: true
